### ISSUE TITLE
oracle支持同时连接两个数据库吗？

### ISSUE THREAD

**Issue by 854770857** [cuyl/egg-oracle#5]
现在有个需求需要同时连接两个oracle 我看配置好像不能同时连接两个数据库

**Comment by cuyl** [comment]
可以的，参见
https://github.com/cuyl/egg-oracle/blob/f9ef4da95b0a52a95fd8c02fc0cb70beeb4fec44/config/config.default.js#L24

**Comment by cuyl** [comment]
没问题我就把 issue 关掉了

**Comment by hsxiaoma** [comment]
请问如何使用呢?

**Comment by cuyl** [comment]
```js
  app.oracle.get('db1')
```
类似 https://eggjs.org/zh-cn/tutorials/mysql.html
